name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sync:
    name: Deno Test
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
    steps:
      - run: apt -qqy update && apt -qqy install unzip
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno test -A ./src/
